version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: oficio
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - .:/var/www
      - ./public:/var/www/public
    networks:
      - app-network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
