version: '3.8'

services:
  mysql:
    image: mysql:8.0               # Aquí se especifica la imagen
    container_name: oficio-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 # Cambia esto
      MYSQL_DATABASE: oficio          # Nombre de la base de datos
      MYSQL_USER: root                # Usuario personalizado
      MYSQL_PASSWORD: 12345678        # Contraseña personalizada
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

